apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    labels:
      app: rsyslog
    name: rsyslog
    namespace: rsyslog
  spec:
    selector:
      matchLabels:
        app: rsyslog
        deploymentconfig: rsyslog
    template:
      metadata:
        annotations:
          openshift.io/container.rsyslog.image.entrypoint: '["/bin/rsyslog.sh"]'
          openshift.io/scc: privileged
        creationTimestamp: null
        labels:
          app: rsyslog
          deploymentconfig: rsyslog
      spec:
        containers:
        - image: registry.access.redhat.com/rhel7/rsyslog:latest
          imagePullPolicy: Always
          name: rsyslog
          resources:
            limits:
              cpu: 100m
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/log
            name: varlog
          - mountPath: /run/log
            name: runlog
          - mountPath: /etc/machine-id
            name: etcmachineid
          - mountPath: /etc/localtime
            name: etclocaltime
          - mountPath: /etc/hostname
            name: etchostname
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
       terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /var/log
          name: varlog
        - hostPath:
            path: /run/log
          name: runlog
        - hostPath:
            path: /etc/machine-id
          name: etcmachineid
        - hostPath:
            path: /etc/localtime
          name: etclocaltime
        - hostPath:
            path: /etc/hostname
          name: etchostname
kind: List
metadata: {}
